name: ESLint checker

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # when using this template, update the node version
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn

      - name: Run ESLint
        run: yarn lint
